# Generated by Django 4.2.18 on 2025-02-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='actual_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='bin',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='legal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
