# Generated by Django 4.2.18 on 2025-02-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_partner_locked_at_partner_locked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
