# Generated by Django 4.2.18 on 2025-02-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partner_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='bin',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contact_person',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_own',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.IntegerField(choices=[(0, 'Company'), (1, 'Individual')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='partner',
            name='trade_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['trade_name'], name='trade_name_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['bin'], name='bin_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['partner_type'], name='partner_type_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['trade_name', 'is_own'], name='trade_name_is_own_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['bin', 'is_own'], name='bin_is_own_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['partner_type', 'is_own'], name='partner_type_is_own_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['trade_name', 'bin'], name='trade_name_bin_idx'),
        ),
    ]
