# Generated by Django 4.2.18 on 2025-02-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_alter_partner_bin_alter_partner_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
