# Generated by Django 4.2.18 on 2025-02-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentrequest_locked_at_paymentrequest_locked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
