# Generated by Django 4.2.18 on 2025-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentrequest_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Panding Approval'), (2, 'Approved'), (3, 'Paid')], default=0),
        ),
    ]
