# Generated by Django 4.2.18 on 2025-02-28 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_paymentrequest_invoice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
